---
- hosts: all
  become: yes

  tasks:

    - name: Create Linux user
      user:
        name: "{{ username }}"
        state: present

    - name: Configure sudo
      copy:
        dest: "/etc/sudoers.d/{{ username }}"
        content: |
          {{ username }} ALL=(ALL) NOPASSWD: ALL
        mode: '0440'
